global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    constraints: "Label(`rp-target`,`main-lb`)"
  # file:
  #   filename: /etc/traefik/dynamic.yml
  #   watch: true

log:
  level: DEBUG
  format: common

certificatesResolvers:
  route53:
    acme:
      email: hygen@hygentrade.com
      dnsChallenge:
        provider: route53
        delayBeforeCheck: 0
        resolvers:
          - 1.1.1.1:53
        # disablePropagationCheck: true
      storage: /certs/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: http
accessLog: {}

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
  private:
    address: ":9443"


